(() => {
  const sessions = {
    home: { tag: '01 // CORE', title: 'Home — La herida se convierte en arquitectura viva', body: 'La portada es la puerta de entrada al universo. El planeta vivo, la máquina orgánica, el diamante y la llave dorada orbitan un mismo núcleo mientras la interfaz presenta el estado del sistema.', items: ['JUDAS_OS v12.0 // OMEGA_CLEAN', 'Nodo JUDAS-CORE-07', 'Enjambre online · Oráculo active', 'Entrada para descubrir las demás sesiones'] },
    artist: { tag: '02 // ORIGIN', title: 'The Artist — Pedro Marcos Santos Belentani', body: 'La sesión de autoría separa la persona pública de la máscara dramática sin romper su relación. São Paulo y Barcelona forman el eje geográfico; la música, la imagen y la tecnología son lenguajes de una misma práctica.', items: ['Creador digital y director audiovisual', 'R&B, pop, electrónica y dark pop', 'DUCK STUDIOS · Manos Abiertas · Cruzando-el-Charco', 'La Defensa del Observador convierte registro en canción'] },
    music: { tag: '03 // SONIC ARCHIVE', title: 'Music — Fragmentos que orbitan la frecuencia', body: 'El archivo sonoro trata cada lanzamiento como una cápsula de memoria recuperada del colapso. Mon Amour, Therapist, Apaga a Luz, Judas, Lento e I Wrote a Song son puertas de escucha y coordenadas del viaje.', items: ['40+ lanzamientos · 36M+ streams declarados', 'Judas Era (Complete) · Mon Amour & Origins', 'The Visual Archive · Studio Sessions', '432 Hz como frecuencia raíz del núcleo'] },
    judas: { tag: '04 // MYTH', title: 'Judas — El beso como umbral', body: 'Judas es máscara, antagonista y algoritmo de evolución mal calibrado. Roba la Llave Dorada para forzar la transformación del Humano, pero descubre que la voz no puede ser poseída.', items: ['El Hombre Integrado', 'La Deuda Impagable', 'El Robo y el Canto', 'La Victoria Amarga · La Mentira Compartida'] },
    experience: { tag: '05 // OMEGA GATE', title: 'The Experience — Zion, Omega y el multiverso', body: 'La experiencia convierte el sitio en una galaxia navegable. OMEGA GATE exige cinco firmas; Zion contiene las líneas temporales colisionadas; Nexus, Void y Mirror describen el último nodo.', items: ['OMEGA GATE · seguridad biométrica nivel 5', 'ZION ORBIT · threat level 3 · uplink stable', 'Warrior & Angel // Multiverse Protocol', 'El visitante actúa como sexta variable de integración'] },
    ailab: { tag: '06 // NEURAL NETWORK', title: 'AI Lab — El enjambre creativo', body: 'El AI Lab es un taller diegético para transformar una directiva en letra, beat, storyboard, biografía, concepto visual o relato. No es un apéndice: es la forma operativa del universo.', items: ['Lyric Assistant · Storyboard · Bio Generator', 'Oráculo Judas · Visual Concept · Beat Concept', 'Sketch Refiner · Mood Color Palette', 'Story Concept Generator · Character Design Generator'] },
    gallery: { tag: '07 // VISUAL ARCHIVE', title: 'Art Gallery — Datos recuperados del colapso', body: 'La galería organiza la estética Judas como registros que pueden mutar: Venom, Gaze, System Halt, Archive, Abduction y Zion Dimension. Cada imagen es una prueba parcial de una historia mayor.', items: ['Neón rojo · desierto · glitch · cristal', 'Warrior / Zion Dimension', 'Record 01 // The Architect', 'Awaiting Upload como estado narrativo'] },
    contact: { tag: '08 // TRANSMISSION', title: 'Contact — Transmitir una frecuencia', body: 'Contacto es el canal humano del sistema. Colaboraciones musicales, proyectos visuales, performances y tecnología creativa entran como transmisiones que pueden abrir nuevos nodos del universo.', items: ['Musical Collaborations', 'Visual Projects', 'Performances', 'Tech & AI · New Music · Exclusive Content'] },
    studio: { tag: '09 // DUCK STUDIOS', title: 'Music Studio — El sonido como arquitectura', body: 'Music Studio es la cámara de producción: un espacio donde una herida se procesa como ritmo, textura, voz y forma. Las sesiones pueden aparecer como archivos, demos o instrumentos del relato.', items: ['Dark pop · R&B alternativo · electrónica industrial', 'JUDAS · Mon Amour · Lento', 'I Wrote a Song · Heart Breaking · Sleep Talking', 'Duck Prod / Duck Studios · Architect of Sound'] }
  };

  const style = document.createElement('style');
  style.textContent = `
    #sessionHub{position:fixed;inset:0;z-index:80;display:none;place-items:center;padding:24px;background:rgba(1,1,3,.78);backdrop-filter:blur(18px) saturate(130%)}
    #sessionHub.open{display:grid;animation:sessionFade .24s var(--ease-out)}
    @keyframes sessionFade{from{opacity:0}to{opacity:1}}
    .session-shell{width:min(1180px,100%);max-height:min(820px,calc(100vh - 48px));overflow:auto;border:1px solid rgba(255,255,255,.16);border-radius:26px;background:linear-gradient(145deg,rgba(18,7,20,.96),rgba(2,2,5,.97));box-shadow:0 30px 120px rgba(0,0,0,.72),0 0 70px rgba(255,0,60,.12);padding:26px}
    .session-head{display:flex;justify-content:space-between;align-items:flex-start;gap:18px;margin-bottom:22px}.session-kicker{color:var(--red-hot);font:700 10px/1.4 ui-monospace,monospace;letter-spacing:.24em;text-transform:uppercase}.session-title{margin:6px 0 4px;font-size:clamp(28px,5vw,58px);letter-spacing:-.045em}.session-title .outline{color:transparent;-webkit-text-stroke:1px var(--red-hot)}.session-subtitle{margin:0;color:rgba(247,251,255,.62);max-width:70ch;font-size:14px;line-height:1.65}.session-close{width:40px;height:40px;border:1px solid rgba(255,255,255,.18);border-radius:50%;background:rgba(255,255,255,.04);font-size:24px;cursor:pointer}.session-close:hover{border-color:var(--red-hot);color:var(--red-hot)}
    .session-grid{display:grid;grid-template-columns:minmax(250px,.8fr) minmax(0,1.6fr);gap:18px}.session-nav{display:grid;gap:8px;align-content:start}.session-nav button{display:grid;grid-template-columns:30px 1fr auto;align-items:center;gap:12px;text-align:left;border:1px solid rgba(255,255,255,.1);border-radius:14px;padding:13px 14px;background:rgba(255,255,255,.035);color:var(--white);cursor:pointer;transition:transform .18s var(--ease-out),border-color .18s,background .18s}.session-nav button:hover,.session-nav button.active{transform:translateX(3px);border-color:rgba(255,40,95,.7);background:linear-gradient(90deg,rgba(255,0,60,.18),rgba(255,255,255,.035))}.session-nav b{color:var(--gold);font:700 10px ui-monospace,monospace}.session-nav strong{font-size:13px;letter-spacing:.04em}.session-nav em{color:var(--muted);font:10px ui-monospace,monospace;font-style:normal;letter-spacing:.12em;text-transform:uppercase}.session-detail{min-height:360px;border:1px solid rgba(255,255,255,.1);border-radius:18px;padding:22px;background:radial-gradient(circle at 92% 8%,rgba(101,247,255,.1),transparent 30%),linear-gradient(145deg,rgba(255,255,255,.06),rgba(255,0,60,.04))}.session-detail .tag{color:var(--gold);font:700 10px ui-monospace,monospace;letter-spacing:.18em;text-transform:uppercase}.session-detail h3{margin:8px 0 12px;font-size:clamp(24px,3vw,38px)}.session-detail p{max-width:68ch;color:rgba(247,251,255,.7);line-height:1.72}.session-detail ul{margin:18px 0 0;padding:0;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;list-style:none}.session-detail li{border-left:2px solid var(--red);padding:10px 12px;background:rgba(0,0,0,.18);color:rgba(247,251,255,.78);font-size:13px;line-height:1.5}.session-status{display:flex;flex-wrap:wrap;gap:8px;margin-top:22px}.session-status span{border:1px solid rgba(101,247,255,.25);border-radius:999px;padding:6px 10px;color:var(--cyan);font:10px ui-monospace,monospace;letter-spacing:.08em}.session-footer{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-top:18px;padding-top:16px;border-top:1px solid rgba(255,255,255,.1);color:var(--muted);font:10px ui-monospace,monospace;letter-spacing:.08em}.session-open-codex{border:1px solid rgba(255,212,92,.4);border-radius:999px;padding:9px 14px;background:rgba(255,212,92,.08);color:var(--gold);cursor:pointer;font:700 10px ui-monospace,monospace;letter-spacing:.12em}
    @media(max-width:780px){#sessionHub{padding:10px}.session-shell{max-height:calc(100vh - 20px);padding:18px}.session-grid{grid-template-columns:1fr}.session-nav{grid-template-columns:repeat(3,minmax(0,1fr))}.session-nav button{display:block;padding:10px 8px}.session-nav b,.session-nav em{display:block;margin-bottom:5px}.session-nav strong{font-size:11px}.session-detail ul{grid-template-columns:1fr}.session-footer{align-items:flex-start;flex-direction:column}}
  `;
  document.head.appendChild(style);

  const hub = document.createElement('section');
  hub.id = 'sessionHub';
  hub.setAttribute('role', 'dialog');
  hub.setAttribute('aria-modal', 'true');
  hub.setAttribute('aria-labelledby', 'sessionHubTitle');
  hub.innerHTML = `<div class="session-shell"><div class="session-head"><div><p class="session-kicker">BELENTANI CORP OS // ARTIST OPERATING SYSTEM</p><h2 id="sessionHubTitle" class="session-title">The <span class="outline">Sessions</span></h2><p class="session-subtitle">Nueve puertas para recorrer al artista, la música, la máscara Judas y el universo OMEGA sin salir de una sola experiencia. Cada sesión es una interfaz del mismo núcleo creativo.</p></div><button class="session-close" type="button" aria-label="Cerrar sesiones">×</button></div><div class="session-grid"><nav class="session-nav" aria-label="Sesiones del artista">${Object.entries(sessions).map(([id,s],i)=>`<button class="${i===0?'active':''}" type="button" data-session="${id}"><b>${String(i+1).padStart(2,'0')}</b><strong>${s.title.split(' — ')[0]}</strong><em>${s.tag.split(' // ')[1]}</em></button>`).join('')}</nav><article class="session-detail" aria-live="polite"></article></div><div class="session-footer"><span>JUDAS-CORE-07 · OMEGA_CLEAN · 432 HZ · UPLINK STABLE</span><button class="session-open-codex" type="button">ABRIR CÓDICE</button></div></div>`;
  document.body.appendChild(hub);

  const detail = hub.querySelector('.session-detail');
  const render = id => {
    const s = sessions[id] || sessions.home;
    detail.innerHTML = `<span class="tag">${s.tag}</span><h3>${s.title}</h3><p>${s.body}</p><ul>${s.items.map(x=>`<li>${x}</li>`).join('')}</ul><div class="session-status"><span>ONLINE</span><span>SYNC 97.3%</span><span>NODE 07</span><span>FREQ 432 HZ</span></div>`;
    hub.querySelectorAll('[data-session]').forEach(btn => btn.classList.toggle('active', btn.dataset.session === id));
  };
  const close = () => hub.classList.remove('open');
  document.getElementById('sessionsBtn')?.addEventListener('click', () => { hub.classList.add('open'); render('home'); });
  hub.querySelector('.session-close').addEventListener('click', close);
  hub.addEventListener('click', event => { if (event.target === hub) close(); });
  document.addEventListener('keydown', event => { if (event.key === 'Escape') close(); });
  hub.querySelectorAll('[data-session]').forEach(btn => btn.addEventListener('click', () => render(btn.dataset.session)));
  hub.querySelector('.session-open-codex').addEventListener('click', () => { close(); document.getElementById('loreBtn')?.click(); });
})();
